// This file is used by Code Analysis to maintain SuppressMessage
// attributes that are applied to this project.
// Project-level suppressions either have no target or are given
// a specific target and scoped to a namespace, type, member, etc.

[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Build", "CA2227:Change 'GroupedFeedItems' to be read-only by removing the property setter.", Justification = "<Pending>", Scope = "member", Target = "~P:Carlton.Dashboard.Components.Feed.FeedViewModel.GroupedFeedItems")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Build", "CA2227:Change 'Statuses' to be read-only by removing the property setter.", Justification = "<Pending>", Scope = "member", Target = "~P:Carlton.Dashboard.ViewModels.ApartmentStatus.ApartmentStatusesViewModel.Statuses")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Build", "CA2227:Change 'Items' to be read-only by removing the property setter.", Justification = "<Pending>", Scope = "member", Target = "~P:Carlton.Dashboard.ViewModels.Contracts.IGroupedItems`1.Items")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Build", "CA2227:Change 'Items' to be read-only by removing the property setter.", Justification = "<Pending>", Scope = "member", Target = "~P:Carlton.Dashboard.ViewModels.Feed.GroupedFeedItems.Items")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Build", "CA2227:Change 'DinnerGuests' to be read-only by removing the property setter.", Justification = "<Pending>", Scope = "member", Target = "~P:Carlton.Dashboard.ViewModels.HomeForDinner.HomeForDinnerViewModel.DinnerGuests")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Build", "CA2227:Change 'Items' to be read-only by removing the property setter.", Justification = "<Pending>", Scope = "member", Target = "~P:Carlton.Dashboard.ViewModels.HouseholdItems.HouseholdItemsViewModel.Items")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Build", "CA2227:Change 'ToDoList' to be read-only by removing the property setter.", Justification = "<Pending>", Scope = "member", Target = "~P:Carlton.Dashboard.ViewModels.ToDos.ToDos.ToDoList")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Build", "CA1724:The type name ApartmentStatus conflicts in whole or in part with the namespace name 'Carlton.Dashboard.ViewModels.ApartmentStatus'. Change either name to eliminate the conflict.", Justification = "<Pending>", Scope = "type", Target = "~T:Carlton.Dashboard.ViewModels.ApartmentStatus.ApartmentStatus")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Build", "CA1717:Only FlagsAttribute enums should have plural names", Justification = "<Pending>", Scope = "type", Target = "~T:Carlton.Dashboard.ViewModels.ApartmentStatus.ApartmentStatuses")]