name: carlton-build-action
on: [push]
jobs:
  check-bats-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-dotnet@v1
      - with:  
          dotnet-version: '5.0.101'
      - run: dotnet build
        
